/* ============================================================
   COMPONO COMPETITOR INTELLIGENCE — DATA FILE
   This is the ONLY file the monthly Claude refresh rewrites.
   Last full refresh: baseline build, June 2026.
   Pricing and headcount figures are approximate — verify on
   first monthly refresh cycle.
   ============================================================ */

const LAST_UPDATED = "11 June 2026 (baseline build - run first monthly refresh to populate Recent Activity)";

const CATEGORIES = {
  hire:    { label: "Hire",    desc: "Pure ATS players. Compono Hire wins on native behavioural insight - most of these are process-only." },
  engage:  { label: "Engage",  desc: "Culture, engagement, personality and behavioural assessment tools. Compono Engage explains how people work, not just how they feel." },
  develop: { label: "Develop", desc: "LMS and capability platforms. Compono Develop tracks what people need, not what they completed." },
  hris:    { label: "HRIS",    desc: "Full-suite platforms that bleed into Hire, Engage or Develop territory. Broad but shallow - they do everything, master nothing." }
};

const COMPETITORS = [

/* ============ HIRE - PURE ATS ============ */
{
  id: "workable",
  name: "Workable",
  category: "hire",
  assessment: { level: "Basic", detail: "Offers cognitive and personality 'Workable Assessments' as an add-on, plus third-party integrations. Generic off-the-shelf tests, not a validated behavioural matching model tied to role or team fit." },
  snapshot: { hq: "Boston, USA (founded Greece)", founded: "2012", funding: "VC-backed, ~US$84M raised", headcount: "~400", anz: "Sells into ANZ, no local office or local support presence" },
  targetMarket: "SMB to mid-market, global, horizontal across industries",
  summary: "High-volume global ATS focused on sourcing reach and speed. Strong job board distribution and an AI sourcing layer.",
  pricing: "Per-job and per-employee tiers. Starter from ~US$169/mo, Standard and Premier tiers scale with headcount. Assessments and texting are paid add-ons.",
  features: ["200+ job board distribution", "AI candidate sourcing and screening", "Interview self-scheduling", "Offer letters and e-signature", "Basic onboarding", "Assessment add-ons", "Mobile app"],
  fabTheirs: { features: "Sourcing reach, AI screening, fast setup", advantages: "Get roles live everywhere quickly with minimal admin", benefits: "Fill roles faster with less manual effort" },
  fabOurs: { features: "ATS with native, validated work personality matching against role and team", advantages: "Speed AND fit in one workflow - no bolt-ons, no generic tests", benefits: "Fewer bad hires and decisions you can defend to executives and boards" },
  wins: ["No native behavioural science - assessments are generic add-ons with no team-fit model", "No ANZ presence or local support", "Speed-first positioning leaves people insight risk completely unaddressed", "Per-job pricing gets expensive at volume"],
  losses: ["Stronger global job board distribution out of the box", "Bigger brand recognition with offshore-headquartered prospects", "Cheaper entry point for very small teams"],
  battlecard: "Workable is built to fill seats fast - and it does that well. But speed is only half the problem. It has no native behavioural layer, so every shortlist is a process decision, not a people decision. When a prospect names Workable, agree on the efficiency, then ask: 'When the role is filled, how confident are you the person will actually fit the team?' That is the gap Compono Hire closes - matching for skills AND fit in the same workflow, with science you can defend.",
  social: "Large global following, high content volume - mostly SEO/recruiting how-to content. Verify current numbers on refresh.",
  recentActivity: []
},
{
  id: "jobadder",
  name: "JobAdder",
  category: "hire",
  assessment: { level: "None", detail: "No native assessment capability. Relies entirely on marketplace integrations for any testing." },
  snapshot: { hq: "Sydney, Australia", founded: "2007", funding: "Private, bootstrapped then PE investment", headcount: "~200", anz: "Strong - ANZ heartland, local support" },
  targetMarket: "Recruitment agencies first, plus in-house teams. SMB to mid-market, strong ANZ base",
  summary: "ANZ-born recruitment platform with agency DNA - built for recruiters managing high requisition volume, expanded into in-house talent teams.",
  pricing: "Per user per month, quote-based. Typically mid-range for ANZ market. Add-ons for premium job boards and integrations.",
  features: ["Agency-grade requisition management", "Strong Seek and ANZ job board integrations", "Candidate database and talent pools", "Placement and temp workflows", "Recruitment CRM", "Marketplace of integrations"],
  fabTheirs: { features: "Agency-grade workflows, deep ANZ job board coverage", advantages: "Built for how ANZ recruiters actually work", benefits: "Local fit and recruiter productivity" },
  fabOurs: { features: "Hiring platform with built-in behavioural matching and organisational psychology foundation", advantages: "Designed for hiring decisions, not just recruitment administration", benefits: "Quality of hire improves, not just speed of placement" },
  wins: ["Zero people insight - purely a process and pipeline tool", "Agency DNA means in-house culture/fit use cases are an afterthought", "No engagement or development story - single product vs platform"],
  losses: ["Very strong ANZ brand and recruiter loyalty", "Deeper agency/temp workflows if prospect runs blended models", "Local incumbency - often already embedded"],
  battlecard: "JobAdder is a strong ANZ recruitment workflow tool with genuine local credibility - do not attack the brand. Reframe the category instead: JobAdder manages the recruitment process; Compono manages the hiring decision. Ask what happens after the shortlist - how do they know who will actually succeed in the team? JobAdder has no answer to that question. We do, natively.",
  social: "Solid ANZ LinkedIn presence, regular recruiter-focused content. Verify on refresh.",
  recentActivity: []
},
{
  id: "teamtailor",
  name: "Teamtailor",
  category: "hire",
  assessment: { level: "Basic", detail: "Partner integrations (e.g. Alva Labs, Thomas) for assessments. Nothing native - candidate experience is the product, not people science." },
  snapshot: { hq: "Stockholm, Sweden", founded: "2013", funding: "Private, profitable, minimal external funding", headcount: "~400", anz: "Growing ANZ push with local team presence" },
  targetMarket: "SMB to mid-market, employer-brand-conscious companies",
  summary: "Employer branding ATS - career site builder plus ATS in one. Wins on candidate experience, design polish and ease of use. Increasingly visible in ANZ deals.",
  pricing: "Per company size, all-inclusive flat model (no per-user fees) - a genuine differentiator they lead with. Quote-based.",
  features: ["Drag-and-drop career site builder", "Modern, candidate-first application flow", "Automation triggers", "Nurture campaigns", "Analytics", "Unlimited users on flat pricing", "Connect (assessment partner marketplace)"],
  fabTheirs: { features: "Career site plus ATS, unlimited users, beautiful UX", advantages: "Employer brand and hiring in one tool everyone can use", benefits: "Better candidate experience, more applicants, simple pricing" },
  fabOurs: { features: "Hiring platform with validated work personality and team-fit matching built in", advantages: "We optimise who you hire, not just how it looks while you hire them", benefits: "Candidate experience AND selection quality - both, not either/or" },
  wins: ["All experience, no insight - polished front door with nothing behind it on selection science", "Assessment story is entirely third-party partners (extra cost, broken workflow)", "Brand-led positioning struggles when prospect's pain is quality of hire, not volume of applicants"],
  losses: ["Genuinely excellent UX and career site builder - design-led buyers love it", "Flat all-inclusive pricing is easy to buy", "Strong momentum and word of mouth in ANZ right now"],
  battlecard: "Teamtailor turns the top of funnel beautiful - and if a prospect's only problem is attracting candidates, it is a credible tool. But attraction is not selection. Ask: 'Once those well-nurtured candidates apply, how does Teamtailor tell you which one will succeed in your team?' It does not - it hands you off to a third-party assessment partner at extra cost. Compono answers that question natively. Both attraction AND selection insight.",
  social: "Very active, design-forward LinkedIn and content presence. Strong employer brand voice. Verify on refresh.",
  recentActivity: []
},
{
  id: "lever",
  name: "Lever",
  category: "hire",
  assessment: { level: "None", detail: "No native assessments - integration partners only. Positioning is CRM-style talent relationship management." },
  snapshot: { hq: "San Francisco, USA (acquired by Employ Inc.)", founded: "2012", funding: "Acquired by Employ (PE-backed) in 2022", headcount: "Part of Employ group", anz: "Sells remotely, no local presence" },
  targetMarket: "Mid-market to enterprise, tech-heavy, US-centric",
  summary: "Talent acquisition suite combining ATS and CRM - built around proactive sourcing and nurture for competitive talent markets.",
  pricing: "Quote-based annual contracts, generally premium mid-market pricing. Modules for CRM, analytics and automation.",
  features: ["ATS + CRM in one (LeverTRM)", "Nurture campaigns", "Advanced analytics", "Automation workflows", "DEI reporting", "Interview scheduling"],
  fabTheirs: { features: "Combined ATS/CRM with nurture and analytics", advantages: "Build pipelines proactively rather than post-and-pray", benefits: "Win competitive talent before competitors do" },
  fabOurs: { features: "Hiring with native behavioural matching and organisational psychology", advantages: "Insight into fit, not just relationship tracking", benefits: "Hire people who stay and perform, not just people you courted well" },
  wins: ["No people science at all - relationships are tracked, fit is guessed", "US-centric, weak ANZ support and localisation (Seek etc.)", "Post-acquisition product investment questions linger"],
  losses: ["Stronger sourcing/CRM motion for proactive enterprise talent teams", "Deeper analytics out of the box", "Recognised name with US-aligned buyers"],
  battlecard: "Lever's pitch is relationship-led hiring - know your candidates before you need them. Reasonable. But knowing someone's email cadence history is not knowing whether they will succeed in the role. Lever tracks the courtship; it cannot assess the marriage. Compono assesses fit with validated science before the offer goes out. In ANZ specifically, also probe local support and Seek integration depth - we are standard, they are not local.",
  social: "Moderate activity, folded increasingly into Employ group messaging. Verify on refresh.",
  recentActivity: []
},
{
  id: "greenhouse",
  name: "Greenhouse",
  category: "hire",
  assessment: { level: "Basic", detail: "Structured interview kits and scorecards (process rigour, not psychometric science) plus a large partner marketplace for actual assessments." },
  snapshot: { hq: "New York, USA", founded: "2012", funding: "PE-owned (TPG majority)", headcount: "~800", anz: "Sells into ANZ enterprise, limited local footprint" },
  targetMarket: "Mid-market to enterprise, strong in tech",
  summary: "The structured hiring ATS - scorecards, interview kits and process discipline. The enterprise benchmark for hiring process rigour.",
  pricing: "Premium quote-based annual contracts, typically the most expensive pure ATS in a deal. Tiered Essential/Advanced/Expert.",
  features: ["Structured interview kits and scorecards", "Deep reporting", "500+ integration marketplace", "DEI tooling", "CRM and events", "Onboarding module"],
  fabTheirs: { features: "Structured hiring methodology embedded in software", advantages: "Consistent, defensible, bias-reduced process at scale", benefits: "Better decisions through process discipline" },
  fabOurs: { features: "Structured process AND validated behavioural data on every candidate", advantages: "Scorecards capture opinions - we add science. Interviewer ratings plus actual work personality fit", benefits: "Defensible decisions built on data, not just well-organised gut feel" },
  wins: ["Scorecards structure human opinion - they do not add objective people data. Process rigour without insight", "Premium pricing - often double alternatives", "Heavy implementation; mid-market teams drown in its complexity"],
  losses: ["Enterprise credibility and brand gravity - 'nobody got fired for buying Greenhouse'", "Deepest integration marketplace in the category", "Genuine thought leadership position on structured hiring"],
  battlecard: "Respect Greenhouse - they taught the market that hiring needs structure. Then extend the argument: structure organises opinions, it does not improve the underlying data. Ten interviewers with beautiful scorecards are still ten gut feels. Compono adds what the scorecard cannot - validated behavioural measurement of fit to role and team. Structure AND science. For mid-market prospects, also press total cost and implementation weight.",
  social: "High-volume thought leadership engine, strong brand. Verify on refresh.",
  recentActivity: []
},
{
  id: "smartrecruiters",
  name: "SmartRecruiters",
  category: "hire",
  assessment: { level: "Basic", detail: "Native screening questions and an assessment partner marketplace. No proprietary behavioural science." },
  snapshot: { hq: "San Francisco, USA", founded: "2010", funding: "VC-backed, ~US$200M+ raised", headcount: "~600", anz: "Enterprise deals only, minimal local presence" },
  targetMarket: "Enterprise and large mid-market, global, high-volume hiring",
  summary: "Enterprise 'hiring success' platform - high-volume requisition management, marketplace ecosystem, positioned as the modern Taleo replacement.",
  pricing: "Enterprise quote-based, priced per employee. Significant annual commitments.",
  features: ["Enterprise requisition workflows", "Marketplace ecosystem", "CRM and sourcing", "AI matching (Winston)", "Global compliance", "Hiring budget management"],
  fabTheirs: { features: "Enterprise-grade hiring infrastructure with AI matching", advantages: "Run global, high-volume hiring on one platform", benefits: "Hiring operations at enterprise scale" },
  fabOurs: { features: "People-science-led hiring built for mid-market reality", advantages: "Right-sized platform with insight depth enterprise suites lack", benefits: "Quality of hire without enterprise overhead" },
  wins: ["AI matching is keyword/CV pattern matching - not validated behavioural science", "Built for enterprise scale; mid-market prospects pay for complexity they will not use", "Weak ANZ presence and support"],
  losses: ["Genuine enterprise scalability and global compliance depth", "Large marketplace ecosystem", "Strong fit for 5,000+ employee organisations - usually out of our sweet spot anyway"],
  battlecard: "SmartRecruiters rarely contests our core mid-market deals - when it does, the prospect is usually over-buying. The honest line: SmartRecruiters is hiring infrastructure for global enterprises; Compono is hiring intelligence for organisations that feel every single hire. Ask how many of its enterprise modules they would actually use, then contrast implementation timelines and the complete absence of validated people science under its AI matching.",
  social: "Active enterprise-focused content, conference-heavy. Verify on refresh.",
  recentActivity: []
},
{
  id: "recruitee",
  name: "Recruitee",
  category: "hire",
  assessment: { level: "None", detail: "No native assessments - integration partners only." },
  snapshot: { hq: "Amsterdam, Netherlands (Tellent group)", founded: "2015", funding: "Merged into Tellent (with Javelo, KiwiHR)", headcount: "~250 (group)", anz: "No local presence" },
  targetMarket: "SMB to lower mid-market, Europe-centric",
  summary: "Collaborative hiring ATS for SMBs - clean UX, easy adoption, priced to land. Part of the Tellent HR group.",
  pricing: "Transparent tiered per-job pricing, entry from ~€199/mo region. One of the cheaper credible options.",
  features: ["Collaborative pipelines", "Career site builder", "Multi-poster job distribution", "Automation", "Referrals", "Basic reporting"],
  fabTheirs: { features: "Simple collaborative ATS the whole team can use", advantages: "Low cost, fast adoption, no training needed", benefits: "Hiring organised without enterprise overhead" },
  fabOurs: { features: "Approachable platform with serious people science underneath", advantages: "Easy to use AND substantive on selection quality", benefits: "Simplicity without sacrificing decision quality" },
  wins: ["Pure process organisation - zero selection insight", "Europe-first; ANZ job boards and support are weak", "Low price reflects low depth - easy to outgrow"],
  losses: ["Cheaper entry point for cost-driven small buyers", "Very low-friction adoption"],
  battlecard: "Recruitee competes on price and simplicity. Do not race to the bottom - reframe value: an ATS that organises bad decisions efficiently still produces bad hires. One mis-hire costs more than years of platform price difference. If the prospect is purely cost-driven and tiny, they may genuinely be a Recruitee customer today and a Compono customer in two years - qualify hard.",
  social: "Moderate, European SMB-focused content. Verify on refresh.",
  recentActivity: []
},
{
  id: "breezy",
  name: "Breezy HR",
  category: "hire",
  assessment: { level: "None", detail: "No native assessment science - questionnaires and third-party integrations only." },
  snapshot: { hq: "Jacksonville, USA (LearnUpon group)", founded: "2014", funding: "Acquired by LearnUpon 2021", headcount: "Part of group", anz: "No local presence" },
  targetMarket: "Small business, budget-conscious",
  summary: "Entry-level SMB ATS with a free tier - drag-and-drop pipelines, simple automation. Volume small-business play.",
  pricing: "Freemium. Free 'Bootstrap' tier, paid tiers from ~US$157/mo. Self-serve.",
  features: ["Drag-and-drop pipeline", "Free tier", "Job board posting", "Candidate questionnaires", "Scheduling", "Basic video interviews"],
  fabTheirs: { features: "Free-to-start, dead simple ATS", advantages: "Zero barrier to organising hiring", benefits: "Stop running hiring from a spreadsheet today" },
  fabOurs: { features: "Hiring platform with behavioural matching for organisations where every hire matters", advantages: "Built for decision quality, not just pipeline tidiness", benefits: "Hires that perform, not just a tidier inbox" },
  wins: ["No science, no insight, no ANZ presence - a spreadsheet replacement", "Free-tier economics mean minimal product depth and support"],
  losses: ["Free is free - unbeatable for the smallest buyers", "Rarely a real competitor in our qualified deals"],
  battlecard: "If Breezy is the genuine alternative, question whether the prospect is qualified - they are likely too small or too early. If they are qualified and anchoring on Breezy's price, the conversation is about the cost of a bad hire vs the cost of software. One mis-hire at $60k+ salary dwarfs any subscription delta.",
  social: "Light presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "zoho-recruit",
  name: "Zoho Recruit",
  category: "hire",
  assessment: { level: "Basic", detail: "Basic pre-screening and assessment add-ons within the Zoho ecosystem. Generic, not behavioural science." },
  snapshot: { hq: "Chennai, India", founded: "2009 (Recruit product)", funding: "Private, profitable (Zoho Corp)", headcount: "Zoho Corp 15,000+", anz: "Sells globally, ecosystem-led" },
  targetMarket: "SMBs already inside the Zoho ecosystem; agencies on a budget",
  summary: "The ATS module of the sprawling Zoho suite. Wins on price and ecosystem bundling, not on hiring depth.",
  pricing: "Aggressively cheap - from ~US$25/user/mo. Bundled into Zoho One.",
  features: ["ATS + recruitment CRM", "Zoho ecosystem integration", "Resume parsing", "Job board posting", "Workflow automation", "Client portals (agency)"],
  fabTheirs: { features: "Full ATS at a fraction of competitor cost, inside your existing Zoho stack", advantages: "One vendor, one bill, everything connected", benefits: "Hiring covered without a new budget line" },
  fabOurs: { features: "Purpose-built hiring intelligence vs a suite checkbox module", advantages: "Hiring is our entire platform thesis, not module #43", benefits: "Selection quality a generalist suite cannot reach" },
  wins: ["Suite-module depth problem - hiring is a checkbox feature, not a competency", "No behavioural science whatsoever", "Support and localisation gaps in ANZ"],
  losses: ["Price is nearly impossible to match", "Ecosystem lock-in is real if they run Zoho everywhere"],
  battlecard: "Zoho Recruit wins on invoice line, never on capability. Concede the price openly - then ask what a suite vendor's 43rd module can know about predicting human performance in their team. The honest framing: Zoho organises recruitment data cheaply; Compono improves hiring decisions. Different categories. If price is the only axis, qualify out gracefully.",
  social: "Large Zoho-corp-level presence, product-line content thin. Verify on refresh.",
  recentActivity: []
},
{
  id: "expr3ss",
  name: "Expr3ss!",
  category: "hire",
  assessment: { level: "Native", detail: "Has its own predictive hiring/psych profiling angle ('Spot On' matching). Closest local philosophical competitor - but proprietary black-box approach with thinner published validation than Compono's organisational psychology foundation." },
  snapshot: { hq: "Australia", founded: "2004", funding: "Private", headcount: "Small (<50)", anz: "ANZ native - this is their entire market" },
  targetMarket: "ANZ SMB to mid-market, high-turnover industries (retail, hospitality, care)",
  summary: "Australian predictive hiring tool - matches candidates on attitude/psych fit for high-volume frontline roles. The most direct local 'fit-based hiring' competitor.",
  pricing: "Quote-based, typically positioned as affordable for volume hiring. Verify current model on refresh.",
  features: ["Predictive 'Spot On' candidate matching", "High-volume screening", "Psych-style profiling", "ANZ job board coverage", "Frontline/volume hiring focus"],
  fabTheirs: { features: "Predictive matching tuned for high-volume frontline hiring", advantages: "Cut screening time dramatically for turnover-heavy roles", benefits: "Faster volume hiring with better retention" },
  fabOurs: { features: "Validated work personality science across hiring, engagement AND development", advantages: "Transparent, published organisational psychology vs proprietary black box - and insight that persists beyond the hire", benefits: "Fit data that keeps working after day one, across the whole employee lifecycle" },
  wins: ["Black-box matching vs our transparent validated model - 'defensible to boards' matters", "Hire-only - no engagement or development continuation of the data", "Frontline/volume niche; weaker for professional and knowledge roles", "Dated platform experience"],
  losses: ["Long-standing ANZ relationships in retail/hospitality/care verticals", "Sharper pricing for pure volume use cases", "Local incumbent familiarity"],
  battlecard: "Expr3ss! validates our category - they prove ANZ buyers want fit-based hiring. The differentiation is depth and continuity: their matching is a proprietary black box scoped to the hire moment; Compono's work personality science is transparent, validated, and flows into engagement and development after the hire. Ask: 'What happens to that fit data on day two?' With Expr3ss! it dies. With Compono it becomes how you manage, engage and grow the person.",
  social: "Light. Verify on refresh.",
  recentActivity: []
},
{
  id: "pageup",
  name: "PageUp",
  category: "hire",
  assessment: { level: "Basic", detail: "Partner-led assessments. Core strength is enterprise talent workflow, not people science." },
  snapshot: { hq: "Melbourne, Australia", founded: "1997", funding: "PE-owned (Battery Ventures)", headcount: "~400", anz: "Strong ANZ enterprise base, especially government, higher ed, healthcare" },
  targetMarket: "ANZ enterprise and large mid-market - government, universities, health",
  summary: "Melbourne-born enterprise talent management suite - recruitment plus onboarding, performance and learning modules. Deeply embedded in ANZ public sector and higher ed.",
  pricing: "Enterprise quote-based annual contracts, premium tier locally.",
  features: ["Enterprise recruitment workflows", "Onboarding", "Performance module", "Learning module", "Strong ANZ compliance", "Public sector depth"],
  fabTheirs: { features: "Enterprise talent suite with ANZ compliance baked in", advantages: "Local enterprise credibility and government-grade process", benefits: "Safe, compliant enterprise talent operations" },
  fabOurs: { features: "People-science platform vs process suite", advantages: "Insight-led where they are workflow-led; right-sized for mid-market", benefits: "Better decisions, faster time to value, without enterprise implementation weight" },
  wins: ["Workflow-deep but insight-shallow - no behavioural science core", "Heavy implementations and enterprise pricing punish mid-market buyers", "Legacy platform feel vs modern experience"],
  losses: ["ANZ enterprise incumbency, especially government and higher ed panels", "Suite breadth across the talent lifecycle", "Procurement-friendly enterprise credentials"],
  battlecard: "PageUp owns ANZ enterprise process - if the deal is a 10,000-seat government panel, it is their turf. In mid-market, flip the weight: their enterprise machinery becomes cost and implementation drag. Ask about time to value and what behavioural insight - not workflow - the platform actually contributes to each hiring decision. Process maturity is not decision quality.",
  social: "Moderate ANZ enterprise presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "livehire",
  name: "LiveHire",
  category: "hire",
  assessment: { level: "None", detail: "No native assessment science - talent community and direct sourcing focus." },
  snapshot: { hq: "Melbourne, Australia", founded: "2011", funding: "Previously ASX-listed (delisted/restructured - verify current status on refresh)", headcount: "~100", anz: "ANZ native plus US direct-sourcing push" },
  targetMarket: "Mid-market to enterprise running talent communities / contingent direct sourcing",
  summary: "Talent community and direct sourcing platform - build engaged candidate pools before requisitions open. Strong in contingent workforce direct sourcing.",
  pricing: "Quote-based, platform plus usage components. Verify current model on refresh.",
  features: ["Live talent communities", "Direct sourcing for contingent work", "Candidate engagement/SMS", "Talent pooling", "ATS integrations"],
  fabTheirs: { features: "Always-on talent communities", advantages: "Source from warm pools instead of cold ads", benefits: "Faster fills from pre-engaged candidates" },
  fabOurs: { features: "Selection science for whoever enters the funnel", advantages: "A warm candidate is not necessarily the right candidate - we tell you who fits", benefits: "Pipeline quality AND selection quality" },
  wins: ["Pooling without insight - warm is not the same as right", "Company stability questions (verify current corporate status)", "Narrow use case vs full hiring platform"],
  losses: ["Genuine differentiation in contingent direct sourcing", "Established ANZ enterprise talent community deployments"],
  battlecard: "LiveHire solves candidate supply; Compono solves candidate selection. They are more often adjacent than competitive - but when positioned head-to-head, ask how a talent community tells you which warm candidate will actually succeed in the team. It cannot. Also worth gently probing vendor stability given their corporate restructuring history.",
  social: "Light-moderate. Verify on refresh.",
  recentActivity: []
},

/* ============ ENGAGE - CULTURE / ENGAGEMENT / PERSONALITY / ASSESSMENT ============ */
{
  id: "culture-amp",
  name: "Culture Amp",
  category: "engage",
  snapshot: { hq: "Melbourne, Australia", founded: "2009", funding: "VC-backed, ~US$400M+ raised, unicorn", headcount: "~1,000", anz: "Strong - Melbourne-founded, major local brand" },
  targetMarket: "Mid-market to enterprise, global, HR/people teams",
  summary: "The engagement survey category leader - employee feedback, performance and development on one platform. The biggest brand in our Engage conversations.",
  pricing: "Per employee per year, quote-based, premium. Modules (Engage, Perform, Develop) priced separately.",
  features: ["Engagement surveys with benchmark library", "Pulse and lifecycle surveys", "Performance reviews and goals", "1-on-1s and feedback", "People analytics", "Skills coach / develop module"],
  fabTheirs: { features: "Science-backed surveys with the industry's largest benchmark dataset", advantages: "Know how you compare and where to act", benefits: "Improve engagement with confidence" },
  fabOurs: { features: "Work personality and culture analytics that explain HOW people work, not just how they feel", advantages: "Feelings data tells you something is wrong; our data tells you why and what to do - down to team composition", benefits: "Culture problems you can actually fix, plus insight that connects to hiring and development" },
  wins: ["Measures sentiment, not work style - they know people are unhappy, not why the team composition makes them unhappy", "Survey fatigue is real and CFOs increasingly question survey ROI", "Personality/behavioural layer is thin vs our validated work personality model", "Premium pricing at scale"],
  losses: ["Massive brand gravity - often the default shortlist name", "Benchmark dataset depth is genuinely unmatched", "Strong performance management module if that is the bundled need", "Local Melbourne hero story"],
  battlecard: "Never dismiss Culture Amp - prospects respect them and so should we. The wedge is the difference between measuring feelings and explaining work. Culture Amp tells you engagement dropped 6 points; it cannot tell you that the team's composition has three competing work styles and no coordinator. Compono Engage explains how people actually work together - which is what you change. Surveys describe the weather; we explain the climate system. Both/and framing works: some clients run both.",
  social: "Very strong - one of the loudest HR tech brands globally. Verify on refresh.",
  recentActivity: []
},
{
  id: "peakon",
  name: "Peakon (Workday)",
  category: "engage",
  snapshot: { hq: "Copenhagen / Workday (Pleasanton, USA)", founded: "2014, acquired by Workday 2021", funding: "Workday-owned", headcount: "Within Workday", anz: "Sold through Workday enterprise motion" },
  targetMarket: "Enterprise, especially existing Workday customers",
  summary: "Continuous listening platform inside Workday - intelligent pulse surveys with driver analytics. Effectively the default for Workday shops.",
  pricing: "Enterprise per-employee, bundled into Workday negotiations.",
  features: ["Continuous intelligent pulse surveys", "Driver and attrition analytics", "Manager dashboards and nudges", "Benchmarking", "Workday ecosystem integration"],
  fabTheirs: { features: "Always-on listening woven into Workday", advantages: "No separate vendor, enterprise-grade analytics", benefits: "Continuous insight inside your existing HRIS" },
  fabOurs: { features: "Work personality and culture analytics independent of any HRIS", advantages: "Explains team dynamics rather than tracking sentiment trends; works with whatever stack you run", benefits: "Actionable team-level insight without Workday lock-in" },
  wins: ["Sentiment trends without behavioural explanation - same gap as all survey tools", "Only compelling inside a Workday estate - irrelevant lock-in for most ANZ mid-market", "Enterprise pricing and motion"],
  losses: ["If the prospect runs Workday, the bundle is hard to dislodge", "Strong continuous-listening analytics engine"],
  battlecard: "Peakon only really appears when Workday is already in the building. If so, do not fight the bundle on survey features - reframe entirely: Peakon listens, Compono explains. Their analytics tell you scores moved; our work personality data tells you the mechanism inside the team that moved them. That insight also feeds hiring and development decisions - something a listening tool structurally cannot do.",
  social: "Folded into Workday corporate presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "lattice",
  name: "Lattice",
  category: "engage",
  snapshot: { hq: "San Francisco, USA", founded: "2015", funding: "VC-backed, ~US$3B peak valuation era", headcount: "~600", anz: "Sells remotely, modest local presence" },
  targetMarket: "Mid-market, tech-leaning, people ops teams",
  summary: "Performance-management-led people platform - reviews, goals, 1:1s with engagement surveys attached. Expanding toward HRIS.",
  pricing: "Per employee per month, modular (~US$11+ pepm as modules stack). Pushes multi-module bundles.",
  features: ["Performance reviews", "OKRs/goals", "1:1s and feedback", "Engagement surveys", "Compensation module", "HRIS ambition (Lattice HRIS)"],
  fabTheirs: { features: "Performance and engagement in one connected system", advantages: "Link how people feel with how they perform", benefits: "A single people-management rhythm" },
  fabOurs: { features: "The missing layer under performance: how people actually work", advantages: "Performance ratings without work-style context misattribute cause; we supply the context", benefits: "Performance conversations grounded in who people are, not just what they scored" },
  wins: ["Process-rich, insight-poor - rituals (reviews, 1:1s) without behavioural understanding", "Module pricing stacks up fast", "HRIS expansion dilutes focus and signals identity drift", "US-centric playbooks for ANZ buyers"],
  losses: ["Slick product experience managers genuinely like", "Strong if the entry pain is performance process, not culture insight", "Loud content/brand machine"],
  battlecard: "Lattice systematises management rituals - reviews, goals, 1:1s. Useful plumbing. But a 1:1 template does not tell a manager that their direct report's work style needs autonomy while the team runs on tight coordination. Compono provides the insight layer those rituals are missing. If the prospect's pain is 'our reviews are chaos', Lattice is credible - probe whether the real pain is 'we do not understand our people', which rituals never fix.",
  social: "Very active content brand. Verify on refresh.",
  recentActivity: []
},
{
  id: "15five",
  name: "15Five",
  category: "engage",
  snapshot: { hq: "San Francisco, USA", founded: "2011", funding: "VC-backed, ~US$80M raised", headcount: "~300", anz: "Remote sales only" },
  targetMarket: "SMB to mid-market, manager-enablement angle",
  summary: "Manager-effectiveness platform - weekly check-ins, engagement surveys, performance and manager training combined.",
  pricing: "Per employee per month tiers (~US$4-14 pepm by module bundle).",
  features: ["Weekly check-ins", "Engagement surveys", "Performance reviews", "High-fives/recognition", "Manager coaching (Transform)", "OKRs"],
  fabTheirs: { features: "Check-ins plus manager development in one", advantages: "Build better managers, not just collect scores", benefits: "Engagement improves because managers improve" },
  fabOurs: { features: "The data managers actually need: how each person works", advantages: "Coaching generic manager skills without person-specific work-style insight is coaching blind", benefits: "Managers adapt to real people, not personas" },
  wins: ["Manager training without people data - generic skills applied blindly", "Check-in fatigue mirrors survey fatigue", "Light analytical depth"],
  losses: ["Manager-enablement angle resonates emotionally with HR buyers", "Cheaper entry point"],
  battlecard: "15Five's bet is that better managers fix engagement - half right. The missing half: a manager cannot adapt to what they cannot see. Compono shows managers exactly how each team member works - then management improvement has a target. Position as the data layer their coaching philosophy needs.",
  social: "Active, manager-focused content. Verify on refresh.",
  recentActivity: []
},
{
  id: "qualtrics",
  name: "Qualtrics EmployeeXM",
  category: "engage",
  snapshot: { hq: "Provo/Seattle, USA", founded: "2002", funding: "PE-owned (Silver Lake, ~US$12.5B take-private)", headcount: "~5,000", anz: "Enterprise presence, local enterprise sales" },
  targetMarket: "Enterprise, experience-management buyers",
  summary: "Enterprise experience management - employee listening as one pillar of a CX/EX mega-platform. Survey science at maximum sophistication.",
  pricing: "Enterprise quote-based, expensive, multi-year.",
  features: ["Advanced survey design and stats engine", "360 feedback", "Lifecycle listening", "Text/sentiment analytics", "EX + CX combined dashboards"],
  fabTheirs: { features: "The most sophisticated listening engine on earth", advantages: "Research-grade rigour at enterprise scale", benefits: "Experience data the board trusts" },
  fabOurs: { features: "Explanation, not just measurement", advantages: "World-class listening still only measures sentiment; we model how people work and fit", benefits: "From knowing the score to changing the system" },
  wins: ["The ultimate measurement tool with the same structural gap - no behavioural work-style model", "Enterprise cost and complexity absurd for mid-market", "Needs analyst resource to extract value"],
  losses: ["Unmatched survey methodology credibility", "Enterprise procurement preference for consolidated XM platforms"],
  battlecard: "Qualtrics appearing in a mid-market deal usually signals an over-scoped RFP. The argument is not survey sophistication - concede it. The argument is that sophistication of measurement cannot fix poverty of explanation. A perfect measure of dissatisfaction still does not say which team dynamics caused it. Compono does, at a price and footprint a mid-market team can actually run.",
  social: "Large corporate presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "leapsome",
  name: "Leapsome",
  category: "engage",
  snapshot: { hq: "Berlin, Germany", founded: "2016", funding: "VC-backed, ~US$60M raised", headcount: "~250", anz: "Remote sales only" },
  targetMarket: "European mid-market, expanding globally",
  summary: "People enablement platform - performance, engagement, learning and compensation modules. European Lattice analogue.",
  pricing: "Modular per employee per month, ~US$8+ pepm as modules stack.",
  features: ["Reviews and goals", "Engagement surveys", "Learning paths", "Compensation", "Meetings/1:1s", "AI summaries"],
  fabTheirs: { features: "All people processes in one modular platform", advantages: "Consolidate point tools", benefits: "One system, lower total cost" },
  fabOurs: { features: "Depth of people insight vs breadth of process modules", advantages: "Consolidated processes on shallow data are consolidated guesswork", benefits: "Decisions improve, not just admin" },
  wins: ["Breadth-over-depth modular play with no behavioural science core", "Minimal ANZ presence, EU-centric support hours", "Same survey-tool explanatory gap"],
  losses: ["Attractive consolidation economics", "Solid product polish"],
  battlecard: "Leapsome sells consolidation - fewer tools, one bill. Fair. But consolidating processes that all run on the same shallow sentiment data does not improve any decision. Ask what the platform actually knows about how their people work. Also probe ANZ support reality for a Berlin-based vendor.",
  social: "Moderate, EU-focused. Verify on refresh.",
  recentActivity: []
},
{
  id: "officevibe",
  name: "Workleap Officevibe",
  category: "engage",
  snapshot: { hq: "Montreal, Canada", founded: "2013 (Workleap group)", funding: "PE investment in Workleap (~CA$125M)", headcount: "~400 (group)", anz: "Remote only" },
  targetMarket: "SMB, team-manager level entry",
  summary: "Lightweight pulse survey and feedback tool inside the Workleap suite - simple, cheap, manager-friendly.",
  pricing: "Cheap per-user tiers, free tier exists. Self-serve.",
  features: ["Automated pulse surveys", "Anonymous feedback", "Recognition (Good Vibes)", "Simple manager reports", "1:1 agendas"],
  fabTheirs: { features: "Effortless pulse surveys teams do not hate", advantages: "Engagement signal with zero admin", benefits: "Know team mood for the price of coffee" },
  fabOurs: { features: "Substantive culture and work personality analytics", advantages: "Mood tracking is a thermometer; we are the diagnosis", benefits: "Insight that drives decisions, not dashboards that drive anxiety" },
  wins: ["Toy-depth analytics - genuinely lightweight", "No behavioural model at all", "SMB tool stretched thin in mid-market"],
  losses: ["Very cheap and frictionless", "Fine for tiny teams that just want a mood check"],
  battlecard: "Rarely a serious head-to-head - Officevibe is a mood thermometer. If a prospect compares us, the qualification question is whether they want to monitor sentiment or change outcomes. Thermometers do not treat fevers.",
  social: "Light-moderate. Verify on refresh.",
  recentActivity: []
},
{
  id: "predictive-index",
  name: "The Predictive Index",
  category: "engage",
  snapshot: { hq: "Westwood, USA", founded: "1955", funding: "PE-backed (General Catalyst era investment)", headcount: "~400 + partner network", anz: "Sold via certified partner network locally" },
  targetMarket: "SMB to mid-market via consultant/partner channel",
  summary: "Veteran behavioural assessment (PI Behavioral Assessment) wrapped in 'talent optimisation' - hire, design, inspire, diagnose framework. Our closest assessment-philosophy competitor.",
  pricing: "Annual platform subscription by employee count, often US$10-30k+/yr, plus paid partner consulting/certification.",
  features: ["PI Behavioral Assessment (4-factor)", "Cognitive assessment", "Job targets/benchmarks", "Team discovery maps", "Partner consulting ecosystem", "Hiring + management use cases"],
  fabTheirs: { features: "60+ years of behavioural assessment heritage", advantages: "Trusted, validated, consultant-supported", benefits: "Talent optimisation with proven science" },
  fabOurs: { features: "Modern work personality science embedded in actual hiring, engagement and development workflows", advantages: "PI is an assessment seeking workflows via consultants and integrations; Compono is the workflow with the science built in", benefits: "Insight at the point of decision - no consultant dependency, no integration tax" },
  wins: ["Standalone assessment requiring consultants and ATS integrations to be operational - cost and friction stack up", "4-factor model is simpler/older than modern validated frameworks", "Partner-channel quality varies wildly", "No ATS, no engagement platform, no LMS - data lives beside the work, not in it"],
  losses: ["Six decades of brand trust in assessment", "Consultant relationships create sticky accounts", "Deep assessment-only credibility if that is all the buyer wants"],
  battlecard: "PI validates behavioural science in hiring - excellent, the category sells itself. The wedge is operationalisation: PI gives you a report and a consultant; Compono gives you the insight inside the hiring, engagement and development workflow itself. Ask what PI costs all-in (platform + consultant + the ATS they still need + integration) vs one platform where the science is native. Heritage is not architecture.",
  social: "Strong US content presence, partner-amplified. Verify on refresh.",
  recentActivity: []
},
{
  id: "sapia",
  name: "Sapia.ai",
  category: "engage",
  snapshot: { hq: "Melbourne, Australia", founded: "2013 (as PredictiveHire)", funding: "VC-backed, ~A$30M+ raised", headcount: "~100", anz: "ANZ native, strong local enterprise logos" },
  targetMarket: "Enterprise volume hiring - retail, contact centres, airlines, banking",
  summary: "AI chat-interview assessment - candidates complete a structured text chat, AI infers personality/communication traits. ANZ-born, volume-hiring focused.",
  pricing: "Enterprise quote-based, usage/volume linked.",
  features: ["Untimed AI chat interview", "Personality + communication inference from text", "Volume screening automation", "Candidate experience focus", "Bias-reduction positioning", "ATS integrations"],
  fabTheirs: { features: "Interview every applicant via AI chat", advantages: "Fair, scalable, loved by candidates", benefits: "Volume screening without human bottleneck" },
  fabOurs: { features: "Validated psychometric work personality measurement vs AI inference from chat text", advantages: "Direct measurement beats linguistic inference for defensibility - and our insight extends past screening into the whole lifecycle", benefits: "Science you can defend to a board, with value beyond the funnel's top" },
  wins: ["AI-inference-from-text faces growing scrutiny vs direct validated measurement - defensibility argument is ours", "Screening-stage only; no engagement/development continuation", "Volume/frontline niche - weaker for professional roles"],
  losses: ["Outstanding candidate experience story and NPS data", "Strong ANZ enterprise logos in volume hiring", "Genuine automation value at extreme volume"],
  battlecard: "Sapia is impressive at the top of high-volume funnels - acknowledge it. Two wedges: first, method - inferring personality from chat text is contested science vs direct validated psychometric measurement, and HR leaders increasingly need AI decisions they can defend. Second, scope - Sapia's insight evaporates after screening; Compono's work personality data lives on through engagement and development. Measurement vs inference, lifecycle vs funnel.",
  social: "Active ANZ presence, AI-ethics-led content. Verify on refresh.",
  recentActivity: []
},
{
  id: "criteria",
  name: "Criteria Corp",
  category: "engage",
  snapshot: { hq: "Los Angeles, USA", founded: "2006", funding: "PE-backed (Sumeru ~US$56M)", headcount: "~200", anz: "Yes - acquired Australian video-interview player Alcami; local presence" },
  targetMarket: "SMB to mid-market, test-led hiring buyers",
  summary: "Pre-employment testing platform - cognitive aptitude (CCAT), personality, emotional intelligence, skills tests plus structured/video interviewing.",
  pricing: "Annual subscription, unlimited-testing tiers by company size (~US$5-15k+/yr typical).",
  features: ["CCAT cognitive aptitude", "Personality and EI tests", "Skills tests library", "Video interviewing (Alcami heritage)", "Score benchmarking", "ATS integrations"],
  fabTheirs: { features: "Broad validated test library, unlimited use", advantages: "Objective data on every candidate cheaply", benefits: "Better screening decisions at flat cost" },
  fabOurs: { features: "Integrated work personality matching vs a standalone test battery", advantages: "Tests bolted beside an ATS create candidate friction and data silos; our science lives inside the hiring flow and persists into the employee lifecycle", benefits: "One platform, one candidate experience, insight that compounds" },
  wins: ["Standalone tool tax - prospect still needs an ATS, integration, and process glue", "Generic tests scored against generic norms, not modelled against their team and culture", "Hire-moment only - no lifecycle continuation"],
  losses: ["Cheap unlimited-testing economics", "CCAT is a respected cognitive instrument", "Local presence via Alcami acquisition"],
  battlecard: "Criteria sells tests; Compono sells decisions. A test score against a national norm is trivia until it is modelled against the actual role and team - which is what our matching does natively, inside the workflow, without a second vendor and integration. If they want cognitive data points, fine. If they want to know who fits, that is us.",
  social: "Moderate. Verify on refresh.",
  recentActivity: []
},
{
  id: "harrison",
  name: "Harrison Assessments",
  category: "engage",
  snapshot: { hq: "Hong Kong / global partner network", founded: "1990", funding: "Private", headcount: "Partner-distributed model", anz: "Active local consultant/partner network" },
  targetMarket: "Mid-market to enterprise via consultants - talent acquisition and development assessment",
  summary: "Veteran assessment house - 'paradox technology' behavioural assessment used for both selection and development, sold heavily through consulting partners.",
  pricing: "Per-assessment and licence models via partners. Verify current structure on refresh.",
  features: ["SmartQuestionnaire (25 min, 175 factors)", "Paradox-based behavioural model", "Job success formulas", "Development and coaching reports", "Engagement analytics add-ons", "Partner consulting delivery"],
  fabTheirs: { features: "Deep paradox-based behavioural measurement for selection and development", advantages: "One assessment, many talent use cases, consultant-guided", benefits: "Rich behavioural depth across the talent lifecycle" },
  fabOurs: { features: "Lifecycle behavioural science delivered as a platform, not a consulting engagement", advantages: "Same lifecycle ambition without per-report economics and consultant dependency - insight is in the workflow your team already runs", benefits: "Scalable, self-serve people insight at platform economics" },
  wins: ["Consultant-mediated delivery = cost, latency and dependency", "Per-assessment economics punish scale", "Assessment reports beside the work vs insight inside the work", "Dated platform experience"],
  losses: ["Genuinely deep assessment instrument respected by practitioners", "Entrenched consultant relationships", "Strong in exec/leadership assessment niches"],
  battlecard: "Harrison's science is credible - the delivery model is the wedge. Reports plus consultants is the 2010 architecture; insight embedded in your hiring, engagement and development workflows is the current one. Ask what each assessment-plus-debrief actually costs at their hiring volume, then compare platform economics where the science is simply part of how work happens.",
  social: "Light, partner-amplified. Verify on refresh.",
  recentActivity: []
},

/* ============ DEVELOP - LMS / CAPABILITY ============ */
{
  id: "go1",
  name: "Go1",
  category: "develop",
  snapshot: { hq: "Brisbane, Australia", founded: "2015", funding: "VC-backed unicorn, ~US$400M+ raised", headcount: "~600", anz: "ANZ-born, strong local presence" },
  targetMarket: "Mid-market to enterprise - content aggregation buyers, often via HRIS/LMS partners",
  summary: "Content aggregator, not an LMS - a Netflix-style library of 100k+ courses from many providers, piped into whatever LMS/HRIS the customer runs.",
  pricing: "Per-user content licence, often bundled through HRIS/LMS partner deals.",
  features: ["100k+ aggregated course library", "Single content subscription across providers", "Embeds into LMS/HRIS platforms", "Compliance content depth", "Curation tooling"],
  fabTheirs: { features: "All the content, one subscription", advantages: "Stop buying courses vendor by vendor", benefits: "Complete content coverage cheaply" },
  fabOurs: { features: "Capability intelligence - knowing WHAT each person needs, not just owning a big library", advantages: "Content abundance without need diagnosis is a bigger haystack; Compono Develop targets the gap first", benefits: "Development that closes actual capability gaps, not completion theatre" },
  wins: ["Content without diagnosis - no model of what each person actually needs", "Not an LMS - still needs a delivery platform", "Completion-tracking world view we explicitly position against"],
  losses: ["Unbeatable content breadth at the price", "Often complementary, not competitive - can sit inside a deal", "ANZ hero brand"],
  battlecard: "Go1 is frequently a partner-shaped object, not an enemy - they sell the haystack, we find the needle. If positioned competitively, the line is simple: 100,000 courses does not answer the only question that matters - what does THIS person need next? Compono Develop starts from capability gaps grounded in work personality and role data. Diagnosis before prescription.",
  social: "Strong ANZ tech brand presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "cornerstone",
  name: "Cornerstone OnDemand",
  category: "develop",
  snapshot: { hq: "Santa Monica, USA", founded: "1999", funding: "PE-owned (Clearlake, ~US$5.2B take-private)", headcount: "~3,000", anz: "Enterprise presence locally" },
  targetMarket: "Large enterprise talent/learning suites",
  summary: "The legacy enterprise LMS giant - learning, performance, content and talent modules at maximum scale and maximum weight.",
  pricing: "Enterprise per-user annual contracts, expensive, long implementations.",
  features: ["Enterprise LMS", "Compliance at scale", "Content marketplace", "Skills graph/AI (Galaxy)", "Performance and succession modules", "Extended enterprise training"],
  fabTheirs: { features: "Everything learning at enterprise scale", advantages: "One vendor for the entire learning estate", benefits: "Governed, compliant, global L&D" },
  fabOurs: { features: "Right-sized capability development tied to people science", advantages: "No 9-month implementation; insight-led not catalogue-led", benefits: "Time to value in weeks, development tied to actual needs" },
  wins: ["Legendary implementation weight and admin burden", "Completion-and-compliance DNA - the exact world view we challenge", "Massively over-scoped for mid-market"],
  losses: ["Enterprise compliance depth genuinely unmatched", "Procurement-safe incumbent for 10,000+ seat estates"],
  battlecard: "Cornerstone in a mid-market deal means someone copied an enterprise RFP. Concede enterprise compliance scale, then contrast: their model tracks what people completed; ours diagnoses what people need. Ask how long their last LMS implementation took and what changed in actual capability afterwards.",
  social: "Large corporate presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "docebo",
  name: "Docebo",
  category: "develop",
  snapshot: { hq: "Toronto, Canada (Italian-founded)", founded: "2005", funding: "Public (NASDAQ: DCBO)", headcount: "~900", anz: "Growing local enterprise presence" },
  targetMarket: "Mid-market to enterprise, internal + external (customer/partner) training",
  summary: "Modern AI-positioned LMS - strong in external/extended enterprise training, content marketplace, and AI-generated learning.",
  pricing: "Quote-based per active user, mid-premium tier.",
  features: ["AI-powered LMS (Docebo Learn)", "External/customer training strength", "Content marketplace", "Learning analytics", "Shape (AI content generation)", "E-commerce for courses"],
  fabTheirs: { features: "AI-native LMS for internal and external audiences", advantages: "One platform for employee, customer and partner learning", benefits: "Modern learning operations with AI leverage" },
  fabOurs: { features: "Capability development driven by who people are, not just AI-assembled content", advantages: "Their AI accelerates content production; our science targets content need", benefits: "Less learning noise, more capability movement" },
  wins: ["AI content generation without need diagnosis just produces more content faster", "External-training strength is irrelevant to internal capability deals", "Still fundamentally completion-paradigm"],
  losses: ["Strong product and AI story momentum", "If extended enterprise (customer training) is in scope, they are genuinely strong"],
  battlecard: "Docebo's AI makes content faster; it does not make development smarter. Faster production of generic learning is the haystack problem with a turbocharger. Compono Develop starts from the person - work personality, role, capability gap - and prescribes accordingly. If the deal includes customer/partner training, qualify carefully; that is their turf, not ours.",
  social: "Active, AI-narrative-led. Verify on refresh.",
  recentActivity: []
},
{
  id: "talentlms",
  name: "TalentLMS",
  category: "develop",
  snapshot: { hq: "San Francisco, USA (Epignosis)", founded: "2012", funding: "Private/PE-backed (Insight Partners)", headcount: "~300 (Epignosis)", anz: "Self-serve global, no local presence" },
  targetMarket: "SMB, self-serve, budget LMS buyers",
  summary: "The leading budget self-serve LMS - quick setup, course authoring, gamification. Volume SMB play from Epignosis.",
  pricing: "Transparent tiers from free up to ~US$500+/mo. Self-serve.",
  features: ["Fast course authoring", "Gamification", "Free tier", "Marketplace content (TalentLibrary)", "Mobile learning", "Simple reporting"],
  fabTheirs: { features: "An LMS live in an afternoon", advantages: "No procurement, no implementation, tiny cost", benefits: "Training organised today" },
  fabOurs: { features: "Capability platform vs course container", advantages: "Hosting courses is solved; knowing what each person needs is not - we solve the unsolved part", benefits: "Development outcomes, not course completions" },
  wins: ["Pure delivery container - zero intelligence about needs", "SMB depth ceiling hit fast", "No people data of any kind"],
  losses: ["Price and setup speed unbeatable at the low end", "Rarely competes in qualified mid-market deals"],
  battlecard: "If TalentLMS satisfies the prospect, their need is course hosting, not capability development - possibly a qualification signal. The honest contrast: TalentLMS stores training; Compono Develop directs it. Different jobs.",
  social: "Moderate SMB content. Verify on refresh.",
  recentActivity: []
},
{
  id: "litmos",
  name: "Litmos",
  category: "develop",
  snapshot: { hq: "San Ramon, USA", founded: "2007 (ex-SAP Litmos, now Francisco Partners)", funding: "PE-owned", headcount: "~300", anz: "NZ-founded heritage, some local base" },
  targetMarket: "Mid-market, compliance and customer training",
  summary: "Established mid-market LMS with strong compliance content library - post-SAP era under PE ownership.",
  pricing: "Quote-based per user, mid-tier.",
  features: ["LMS core", "Large off-the-shelf compliance library", "Customer training", "Integrations (Salesforce etc.)", "AI assistant features"],
  fabTheirs: { features: "LMS plus ready-made compliance content", advantages: "Tick compliance boxes fast", benefits: "Low-effort training coverage" },
  fabOurs: { features: "Development intelligence beyond compliance box-ticking", advantages: "Compliance is table stakes; capability movement is the game", benefits: "Develop people, not just satisfy auditors" },
  wins: ["Compliance-content DNA equals completion paradigm", "Post-acquisition drift questions", "No people insight layer"],
  losses: ["Compliance library is genuinely convenient", "Established mid-market base"],
  battlecard: "Litmos sells audit safety. If that is the whole need, fine - but ask the prospect what changed in actual team capability after last year's completions hit 100%. Silence is our opening. Compono Develop is for organisations who want development to mean something.",
  social: "Light-moderate. Verify on refresh.",
  recentActivity: []
},
{
  id: "learnupon",
  name: "LearnUpon",
  category: "develop",
  snapshot: { hq: "Dublin, Ireland", founded: "2012", funding: "PE-backed (Summit Partners US$56M)", headcount: "~300", anz: "Sydney office - real local presence" },
  targetMarket: "Mid-market, multi-audience training (employee + customer + partner)",
  summary: "Clean multi-portal LMS - one platform serving employee, customer and partner training audiences. Strong support reputation.",
  pricing: "Quote-based annual tiers by active users, mid-tier.",
  features: ["Multi-portal architecture", "Employee + customer + partner training", "Course authoring", "Integrations", "Strong support reputation", "Reporting"],
  fabTheirs: { features: "Multiple training audiences, one LMS", advantages: "Consolidate internal and external training", benefits: "Operational simplicity across audiences" },
  fabOurs: { features: "Internal capability intelligence vs multi-audience delivery", advantages: "They optimise delivery breadth; we optimise development relevance", benefits: "The right development for each person, not the same portal for everyone" },
  wins: ["Delivery-focused, no diagnosis layer", "Multi-audience strength irrelevant in internal-only deals", "Completion paradigm"],
  losses: ["Genuine local presence (Sydney)", "Well-liked support", "Strong if customer training is in scope"],
  battlecard: "LearnUpon runs clean training operations - if the prospect's problem is operational (portals, audiences, admin), they are credible. If the problem is 'our people are not developing the capabilities we need', no portal architecture answers that. Compono Develop does - by knowing the person before prescribing the path.",
  social: "Moderate. Verify on refresh.",
  recentActivity: []
},
{
  id: "360learning",
  name: "360Learning",
  category: "develop",
  snapshot: { hq: "Paris, France", founded: "2013", funding: "VC-backed, ~US$240M raised", headcount: "~400", anz: "Remote sales only" },
  targetMarket: "Mid-market to enterprise, L&D teams bought into collaborative learning",
  summary: "Collaborative learning platform - internal experts author courses, peers co-build knowledge. 'Learning from your own people' philosophy.",
  pricing: "Per registered user per month (~US$8 pepm entry) plus platform tiers.",
  features: ["Collaborative course authoring", "Subject-expert-led content", "Reactions/co-editing", "AI authoring assists", "Academies", "Skills features"],
  fabTheirs: { features: "Turn internal experts into course creators", advantages: "Relevant institutional knowledge beats generic libraries", benefits: "Learning culture powered by your own people" },
  fabOurs: { features: "Knowing who needs what, before deciding who teaches it", advantages: "Collaborative authoring still needs a needs-model; peer content without diagnosis is well-meaning noise", benefits: "Collaboration aimed at actual capability gaps" },
  wins: ["Authoring philosophy without need diagnosis", "Depends heavily on internal authoring energy - fades after launch enthusiasm", "No people science layer"],
  losses: ["Compelling philosophy for L&D believers", "Good product experience"],
  battlecard: "360Learning answers 'who creates content' - internal experts, nice. It does not answer 'what does each person need' - which is the prior question. Compono Develop sequences it correctly: diagnose the capability gap from real people data, then source content (theirs, ours, anyone's). Philosophy second, diagnosis first.",
  social: "Active, philosophy-led content. Verify on refresh.",
  recentActivity: []
},

/* ============ HRIS - FULL SUITE OVERLAP ============ */
{
  id: "employment-hero",
  name: "Employment Hero",
  category: "hris",
  snapshot: { hq: "Sydney, Australia", founded: "2014", funding: "VC-backed unicorn, A$2B+ valuation era", headcount: "~1,000", anz: "ANZ native, aggressive local growth" },
  targetMarket: "ANZ SMB to lower mid-market, payroll-led",
  summary: "ANZ employment super-app - HRIS, payroll, benefits, hiring (Swag/SmartMatch) and engagement features in one aggressive bundle. The loudest local consolidator.",
  pricing: "Per employee per month tiers, payroll-bundled, aggressive discounting.",
  features: ["HRIS + payroll core", "Hiring module + SmartMatch talent pool", "Engagement surveys (basic)", "Learning module (basic)", "Benefits/Swag app", "Compliance (ANZ awards)"],
  fabTheirs: { features: "Employment, end to end, one ANZ platform", advantages: "Consolidate HR, payroll and hiring into one bill", benefits: "Less admin, fewer vendors, local compliance handled" },
  fabOurs: { features: "Depth where it decides outcomes: hiring, engagement, development on real people science", advantages: "Suite modules are checkbox-deep; people decisions deserve specialist depth", benefits: "Run payroll wherever you like - make people decisions on science" },
  wins: ["Hiring/engagement/learning modules are shallow checkbox features vs specialist depth", "No behavioural science anywhere in the stack", "Land-and-expand pricing creep frustrates customers", "Their breadth is our both/and: keep their payroll, add our intelligence"],
  losses: ["Consolidation economics are seductive for SMBs", "Massive ANZ brand momentum and channel (accountants)", "Payroll gravity - owning payroll makes everything else sticky"],
  battlecard: "Never fight Employment Hero on payroll - concede it, even compliment it. The wedge: ask the prospect to open the hiring or engagement module and find the science. There is none - they are admin features wearing product names. Compono coexists: keep EH for employment admin, use Compono for the decisions that determine who you employ and how they perform. Both/and beats rip-and-replace, and it defuses their consolidation pitch.",
  social: "Very loud ANZ presence, aggressive marketing. Verify on refresh.",
  recentActivity: []
},
{
  id: "elmo",
  name: "ELMO Software",
  category: "hris",
  snapshot: { hq: "Sydney, Australia", founded: "2002", funding: "PE-owned (K1 take-private from ASX, ~A$486M)", headcount: "~600", anz: "ANZ/UK mid-market staple" },
  targetMarket: "ANZ mid-market HR suites - 200-2,000 employees",
  summary: "The ANZ mid-market HR suite incumbent - modular HRIS spanning recruitment, onboarding, performance, learning, payroll. The most frequent suite incumbent in our deals.",
  pricing: "Modular per-module per-employee annual contracts. Multi-module bundles discounted.",
  features: ["Modular HRIS core", "Recruitment module", "Performance module", "Learning module + course library", "Payroll", "Surveys (basic)"],
  fabTheirs: { features: "Pick-your-modules ANZ HR suite", advantages: "One local vendor, broad coverage, procurement-friendly", benefits: "HR consolidated with a known local name" },
  fabOurs: { features: "Specialist people-science platform vs module catalogue", advantages: "Every ELMO module is a workflow; none contains insight. We are insight-first across hire, engage, develop", benefits: "Decisions improve, not just processes digitise" },
  wins: ["Module breadth, insight zero - no behavioural science anywhere", "Post-take-private product investment perceptions worth probing", "Modules individually beatable by every specialist", "Survey-basic engagement vs our explanatory depth"],
  losses: ["Entrenched mid-market incumbency - often already installed", "Procurement preference for module consolidation", "Local brand familiarity and compliance trust"],
  battlecard: "ELMO is usually the incumbent, so the motion is displacement or coexistence, not bake-off. Probe satisfaction module by module - recruitment and learning are commonly the weakest-loved. The line: ELMO digitised your HR processes; it never improved a single people decision. Compono can sit beside the ELMO core and own the decision layer - hiring, engagement insight, capability - where workflow tools structurally cannot follow.",
  social: "Moderate ANZ presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "rippling",
  name: "Rippling",
  category: "hris",
  snapshot: { hq: "San Francisco, USA", founded: "2016", funding: "VC mega-backed, US$13B+ valuation era", headcount: "~3,000", anz: "Launched ANZ (Sydney) - expanding aggressively with local payroll" },
  targetMarket: "SMB to mid-market, ops/finance-led buyers consolidating HR+IT+finance",
  summary: "The employee-graph super-platform - HR, IT (devices/apps) and finance on one system. Hyper-aggressive global expansion including ANZ payroll.",
  pricing: "Modular per employee per month, starts cheap, stacks fast. Quote-based bundles.",
  features: ["HRIS + global payroll", "Device/app management (IT)", "Spend/finance modules", "Recruiting module (basic ATS)", "Learning module (basic)", "Workflow automation engine"],
  fabTheirs: { features: "HR, IT and finance unified on the employee graph", advantages: "Onboard once, everything provisions automatically", benefits: "Operational consolidation no rival matches" },
  fabOurs: { features: "People intelligence vs operational automation", advantages: "Rippling automates the admin around an employee; we inform the decisions about the human", benefits: "Provision laptops with Rippling; choose and grow people with Compono" },
  wins: ["People modules (recruiting, learning, engagement) are checkbox-thin vs the ops core", "Zero behavioural science", "Ops/IT-led buying centre often is not our buyer anyway - coexistence framing easy", "ANZ depth (awards, local nuance) still maturing despite the launch"],
  losses: ["Ferocious product velocity and funding", "Consolidation pitch resonates with cost-cutting CFOs", "Slick demo experience"],
  battlecard: "Rippling's genius is admin automation - conceding that costs nothing because it is not our category. The reframe: Rippling treats an employee as a record to provision; Compono treats them as a human to understand. No employee graph tells you whether a candidate fits the team or why a team is misfiring. Coexistence is natural: their rails, our intelligence. Watch their ANZ localisation claims closely on refresh - it is moving fast.",
  social: "Extremely loud, high-velocity marketing. Verify on refresh.",
  recentActivity: []
},
{
  id: "bamboohr",
  name: "BambooHR",
  category: "hris",
  snapshot: { hq: "Lindon, Utah, USA", founded: "2008", funding: "Private, profitable, minimal external capital", headcount: "~1,200", anz: "Sells remotely, US-centric" },
  targetMarket: "Global SMB HRIS, HR-led buyers",
  summary: "The friendly SMB HRIS benchmark - core HR records, time off, basic ATS, performance and eNPS surveys. Beloved UX, deliberately simple.",
  pricing: "Per employee per month tiers (~US$6-12 pepm region), self-serve-ish.",
  features: ["Core HRIS records", "Time off/leave", "Basic ATS", "Onboarding", "Performance basics", "eNPS/wellbeing surveys"],
  fabTheirs: { features: "HR basics done beautifully", advantages: "Loved by employees and admins alike", benefits: "HR foundation without complexity" },
  fabOurs: { features: "The intelligence layer SMB suites do not attempt", advantages: "Bamboo manages records; we improve decisions - different jobs, often complementary", benefits: "Keep the friendly HRIS; add the people science" },
  wins: ["ATS and survey features are deliberately basic - no science, no depth", "US-centric (leave/compliance localisation gaps for ANZ)", "Coexistence story trivial to tell"],
  losses: ["Genuinely loved product with loyal advocates", "Simple economics for small teams"],
  battlecard: "BambooHR rarely deserves attack - it is a records system people like. When prospects conflate it with a hiring or engagement solution, gently separate the jobs: Bamboo stores what happened to employees; Compono informs what should happen next. The basic ATS comparison wins itself on one demo of behavioural matching.",
  social: "Strong SMB content brand. Verify on refresh.",
  recentActivity: []
},
{
  id: "sage-hr",
  name: "Sage HR / Sage People",
  category: "hris",
  snapshot: { hq: "Newcastle, UK (Sage Group)", founded: "Sage 1981; HR via acquisitions", funding: "Public (LSE: SGE)", headcount: "11,000+ (group)", anz: "Present via Sage accounting ecosystem" },
  targetMarket: "SMB (Sage HR) and mid-market (Sage People) inside Sage finance estates",
  summary: "HR modules of the Sage accounting empire - bought where Sage finance already runs. Solid records, shallow people features.",
  pricing: "Modular per employee per month, low entry (Sage HR), enterprise quotes (Sage People).",
  features: ["Core HR records", "Leave management", "Basic performance", "Basic recruitment module", "Sage finance ecosystem integration", "Payroll links"],
  fabTheirs: { features: "HR attached to the finance system you already trust", advantages: "One vendor relationship, finance-grade reliability", benefits: "Low-risk HR digitisation" },
  fabOurs: { features: "People decisions need people science, not an accounting vendor's HR module", advantages: "Ecosystem convenience does not assess fit, explain culture, or close capability gaps", benefits: "Keep Sage for money; use Compono for people" },
  wins: ["HR is a side-business of an accounting company - depth reflects it", "No behavioural anything", "Easy coexistence framing"],
  losses: ["Ecosystem gravity where Sage finance is entrenched", "Cheap bundled economics"],
  battlecard: "Sage HR appears via the accountant channel, not HR strategy. The respectful line: Sage is excellent at money and adequate at records - nobody, including Sage, claims it understands people. When the conversation is about who to hire or why a team underperforms, Sage has no entry. We do.",
  social: "Group-level corporate presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "humanforce",
  name: "Humanforce",
  category: "hris",
  snapshot: { hq: "Sydney, Australia", founded: "2002 (as TimeTarget)", funding: "PE-owned (A-P Capital era; acquired intelliHR, LiveSalary)", headcount: "~400", anz: "ANZ native, frontline-workforce focus" },
  targetMarket: "ANZ frontline/deskless industries - care, hospitality, retail, mining services",
  summary: "Frontline workforce management suite - rostering, time and attendance core, plus HRIS, payroll and (via intelliHR acquisition) people analytics and engagement.",
  pricing: "Per employee per month modular, workforce-management-led bundles.",
  features: ["Rostering/scheduling core", "Time and attendance", "Award interpretation (ANZ)", "HRIS + payroll", "intelliHR people analytics/engagement", "Frontline employee app"],
  fabTheirs: { features: "Frontline workforce ops end to end, ANZ-compliant", advantages: "Built for shift-based reality, awards handled", benefits: "Deskless workforce managed properly" },
  fabOurs: { features: "Who to hire and how teams work - questions rostering never answers", advantages: "intelliHR added dashboards, not behavioural science; scheduling hours is not understanding humans", benefits: "Fit-based hiring and culture insight for the same frontline teams they roster" },
  wins: ["People analytics (intelliHR) is reporting, not behavioural insight", "Hiring capability minimal - rostering DNA", "Coexistence natural: they schedule the workforce we helped select"],
  losses: ["Deep frontline/awards moat in ANZ", "Entrenched in care/hospitality verticals we also target"],
  battlecard: "Humanforce owns the roster; the open question is who deserves to be on it. In shared verticals (care especially), the pitch is sequential: Compono selects for personality and care quality - per our childcare/early-learning positioning - and explains team dynamics; Humanforce schedules the result. If their intelliHR module is raised, distinguish dashboards about people from science about how people work.",
  social: "Moderate ANZ presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "dayforce",
  name: "Dayforce (Ceridian)",
  category: "hris",
  snapshot: { hq: "Minneapolis, USA", founded: "1992 (Ceridian lineage), rebranded Dayforce 2024", funding: "Public (NYSE: DAY)", headcount: "~9,000", anz: "Established ANZ enterprise payroll presence" },
  targetMarket: "Enterprise HCM - payroll-led, 1,000+ employees",
  summary: "Enterprise HCM with a celebrated continuous-calculation payroll engine - HR, workforce management, talent modules attached to the payroll core.",
  pricing: "Enterprise per-employee contracts, payroll-anchored, premium.",
  features: ["Continuous-calc payroll engine", "Workforce management", "HR core", "Recruiting module", "Talent/learning modules", "Wallet (on-demand pay)"],
  fabTheirs: { features: "Real-time payroll plus full HCM", advantages: "One enterprise system anchored on payroll accuracy", benefits: "Compliance and cost control at scale" },
  fabOurs: { features: "Decision intelligence enterprise HCM modules never contain", advantages: "Their talent modules exist to tick RFP boxes beside payroll; ours exist because people science is the whole product", benefits: "Enterprise payroll AND genuine people insight - different vendors, both excellent" },
  wins: ["Talent modules are RFP-grade, not decision-grade - no science", "Enterprise weight irrelevant below 1,000 seats", "Coexistence framing with payroll incumbency"],
  losses: ["Payroll engine genuinely superb - immovable where installed", "Enterprise procurement consolidation pressure"],
  battlecard: "Dayforce deals are payroll deals wearing HCM clothes. Never contest payroll. The opening: ask which Dayforce talent module the HR team actually loves - the answer is reliably none. Compono coexists as the people-decision layer above any payroll spine. Both/and, zero rip-out.",
  social: "Large corporate presence. Verify on refresh.",
  recentActivity: []
},
{
  id: "ukg",
  name: "UKG",
  category: "hris",
  snapshot: { hq: "Lowell/Weston, USA", founded: "2020 merger (Ultimate + Kronos)", funding: "PE-owned (Hellman & Friedman), ~US$22B+ valuation era", headcount: "~15,000", anz: "Workforce-management-led local presence (Kronos heritage)" },
  targetMarket: "Enterprise HCM and workforce management",
  summary: "HCM giant from the Ultimate-Kronos merger - workforce management heritage (Kronos) plus full HCM (Pro). Enterprise scale, culture-marketing-heavy ('Great Place To Work' ownership).",
  pricing: "Enterprise contracts, premium, payroll/WFM-anchored.",
  features: ["Workforce management (Kronos lineage)", "Full HCM suite (Pro)", "Payroll", "Talent modules", "Great Place To Work survey assets", "AI assistant (Bryte)"],
  fabTheirs: { features: "Enterprise HCM plus the workforce management gold standard", advantages: "Scale, compliance, and culture credentials (GPTW)", benefits: "People operations for the largest workforces" },
  fabOurs: { features: "Owning a survey brand is not the same as explaining how people work", advantages: "GPTW badges measure perception; Compono models actual work personality and team dynamics", benefits: "Culture you can engineer, not just certify" },
  wins: ["Talent/culture features are certification-and-survey paradigm - the exact gap we exploit", "Enterprise-only relevance; rare in our segment", "Module depth thin outside payroll/WFM"],
  losses: ["Enormous enterprise installed base", "GPTW brand halo in culture conversations"],
  battlecard: "UKG rarely meets us directly below enterprise. When the GPTW halo enters a culture conversation, the distinction is sharp: a Great Place To Work certificate describes how people felt last quarter; Compono explains how your specific people work and what your teams need next. Certification is marketing; explanation is management.",
  social: "Large corporate presence. Verify on refresh.",
  recentActivity: []
}
];
